sudo: required

services:
  - docker
  
install:
  - docker build -t fpsom/jupyter-kernels .
  - docker run -d -p 8888:8888 fpsom/jupyter-kernels

script:
  - docker ps | grep -q fpsom/jupyter-kernels
